/simulated_reservoir_node:
  ros__parameters:
    # Reservoir selection
    reservoir_type: "double_pendulum"
    
    # Nested reservoir-specific parameters
    reservoir_parameters:
        xml_file: "simulated_double_pendulum.xml"
        dt_ctrl: 0.05
        mujoco_substeps: 5
        rbf_gamma: 0.05
        rbf_components: 1000
        ctrl_scale: 12.0
        leak_rate: 0.3
        seed: 42
        warmup_steps: 30
      
/expert_trainer_node:
  ros__parameters:
    # Reservoir selection
    reservoir_type: "double_pendulum"
    dt: 0.05 # dt is the amount of time per control loop, which should be equal to the dt_ctrl * mujoco_substeps

    # TODO: Add in expert controller parameters. Use defaults in source code for now
    
    # Nested reservoir-specific parameters
    reservoir_parameters:
        xml_file: "simulated_double_pendulum.xml"
        dt_ctrl: 0.01 # dt_ctrl is the amount of time per mujoco_substep. should be aligned with .xml specification
        mujoco_substeps: 5 # number of steps to make on every step() call
        rbf_gamma: 0.05
        rbf_components: 1000
        ctrl_scale: 12.0
        leak_rate: 0.3
        seed: 42
        warmup_steps: 30
      